# Generated by Django 4.2.7 on 2023-11-21 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0002_studentprofile_bits_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='password',
        ),
        migrations.AddField(
            model_name='menu',
            name='month_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='about_you',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
