# Generated by Django 4.2.7 on 2023-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0004_alter_menu_month_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bits_id',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='hostel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='personal_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
