# Generated by Django 4.2.7 on 2023-11-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0006_staffprofile_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuDate',
        ),
    ]
