# Generated by Django 4.2.7 on 2023-11-24 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0007_rename_menu_menudate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu',
            new_name='meal',
        ),
        migrations.AlterField(
            model_name='menudate',
            name='month_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
