# Generated by Django 4.2.7 on 2023-11-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0010_rename_meal_menuitem_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu',
            new_name='meal',
        ),
    ]
