# Generated by Django 4.2.7 on 2023-11-24 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0011_rename_menu_menuitem_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudate',
            name='month_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
