# Generated by Django 4.2.7 on 2023-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0012_alter_menudate_month_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images'),
        ),
    ]
