# Generated by Django 4.2.7 on 2023-11-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0013_alter_complaint_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
