# Generated by Django 4.2.7 on 2023-11-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0014_delete_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
