# Generated by Django 4.2.7 on 2023-11-29 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0016_remove_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_feedback',
            field=models.DateField(default=datetime.date(2023, 11, 29)),
        ),
    ]
