# Generated by Django 4.2.7 on 2023-12-01 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessDeck', '0025_alter_complaint_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudate',
            name='breakfast_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menudate',
            name='dinner_items',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menudate',
            name='lunch_items',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_feedback',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
